version: "3.9"

services:
  api:
    image: kepler-api
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - SERVER=db:27017
      - DATABASE=Kepler-22B
    restart: on-failure
    networks:
      - app-network
    expose:
      - "8000"
    deploy:
      replicas: 3
      restart_policy: 
        condition: on-failure
  
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api 
      - db
    networks:
      - app-network
    deploy: 
      restart_policy: 
        condition: on-failure
  
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    restart: on-failure
    networks:
      - app-network
    deploy:
      restart_policy: 
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

volumes:
  dbdata:

networks:
  app-network:
    external: true