export interface VideoItem {
  id: number;
  name: string;
  time: string;
  type: "youtube" | "drive" | "live";
  link: string;
  image: string;
  duration?: string;
  views?: string;
  isCompleted?: boolean;
  isLocked?: boolean;
  chapter?: string;
  difficulty?: "beginner" | "intermediate" | "advanced";
}

export const playlistData: { [key: string]: VideoItem[] } = {
  dsa: [
    {
      id: 1,
      name: "GFG POTD 19/8/2025",
      time: "45:30",
      type: "drive",
      link: "https://drive.google.com/file/d/15uQmVE9Lw27VkwIkqHQF4s5qApTsOye7/preview",
      image: "https://i.ytimg.com/vi/ZOk-OJpovA0/hqdefault.jpg?s…BACGAY4AUAB&rs=AOn4CLBxA0Hz6heRGZ1RDc_FQLtCNIy_WA",
      duration: "45:30",
      views: "12.5K",
      isCompleted: true,
      chapter: "Chapter 1: Calculus Basics",
      difficulty: "beginner",
    },
    {
      id: 2,
      name: "GFG POTD 20/8/2025",
      time: "52:15",
      type: "youtube",
      link: "https://youtu.be/uLWgzhrwqxE?si=0TyB-6-MZzeN6OjH",
      image: "https://i.ytimg.com/vi/uLWgzhrwqxE/hqdefault.jpg?s…BACGAY4AUAB&rs=AOn4CLDMlrjhzASJ23D_HcnI2Onk1E8adw",
      duration: "52:15",
      views: "8.9K",
      isCompleted: false,
      chapter: "Chapter 2: Differential Equations",
      difficulty: "intermediate",
    },
    {
      id: 3,
      name: "GFG POTD 21/8/2025",
      time: "38:45",
      type: "youtube",
      link: "https://youtu.be/sex3ZyedK-c?si=PlPJCRh0tVAsoZiT",
      image: "https://i.ytimg.com/vi/sex3ZyedK-c/hqdefault.jpg?s…BACGAY4AUAB&rs=AOn4CLBSrLF6klJFjX5Df9-JlLSodnD3DA",
      duration: "38:45",
      views: "15.2K",
      isCompleted: false,
      isLocked: false,
      chapter: "Chapter 3: Linear Algebra",
      difficulty: "advanced",
    },
    {
      id: 4,
      name: "GFG POTD 22/8/2025",
      time: "67:22",
      type: "live",
      link: "https://youtu.be/LpSZNZU3BNo?si=21C_c3VsCfOz7blg",
      image: "https://img.youtube.com/vi/iufGu7FuQRY/maxresdefault.jpg",
      duration: "67:22",
      views: "6.1K",
      isCompleted: false,
      chapter: "Chapter 4: Complex Analysis",
      difficulty: "advanced",
    },
    {
      id: 5,
      name: "GFG POTD 23/8/2025",
      time: "41:18",
      type: "youtube",
      link: "https://youtu.be/vespTK1Ri0c?si=iTRLxww4CYLcvf_S",
      image: "https://i.ytimg.com/vi/LpSZNZU3BNo/hqdefault.jpg?s…BACGAY4AUAB&rs=AOn4CLAEA_Acftnqm41-vQymMHBUtfjWvA",
      duration: "41:18",
      views: "9.7K",
      isCompleted: false,
      chapter: "Chapter 5: Statistics",
      difficulty: "intermediate",
    },
    {
      id: 6,
      name: "GFG POTD 24/8/2025",
      time: "41:18",
      type: "drive",
      link: "https://youtu.be/s3vm6rLWDAg?si=ibMLwkJKayDUi5uJ",
      image: "https://i.ytimg.com/vi/vespTK1Ri0c/hqdefault.jpg?s…BACGAY4AUAB&rs=AOn4CLDuZwMEIOWviz_a5cD9BWfTPl9aDw",
      duration: "41:18",
      views: "9.7K",
      isCompleted: false,
      chapter: "Chapter 5: Statistics",
      difficulty: "intermediate",
    },
  ],
  ml: [
    {
      id: 1,
      name: "GFG POTD 25/8/2025",
      time: "55:30",
      type: "youtube",
      link: "https://youtu.be/rl3_zPFaRR4?si=yMmfoc6gh3098OOQ",
      image: "https://i.ytimg.com/vi/s3vm6rLWDAg/hqdefault.jpg?s…BACGAY4AUAB&rs=AOn4CLCRof_-uxjqywxEc5WyQFoCMiS0ig",
      duration: "55:30",
      views: "25.3K",
      isCompleted: true,
      chapter: "Physics - Mechanics",
      difficulty: "intermediate",
    },
    {
      id: 2,
      name: "GFG POTD 26/8/2025",
      time: "55:30",
      type: "youtube",
      link: "https://youtu.be/eMKMFv1-SNo?si=R2_xJp-FziongJgo",
      image: "https://i.ytimg.com/vi/rl3_zPFaRR4/hqdefault.jpg?s…BACGAY4AUAB&rs=AOn4CLCNlC8Cv90zhEeoyr2nxngKP9rD1Q",
      duration: "55:30",
      views: "25.3K",
      isCompleted: true,
      chapter: "Physics - Mechanics",
      difficulty: "intermediate",
    },
    {
      id: 3,
      name: "GFG POTD 27/8/2025",
      time: "55:30",
      type: "youtube",
      link: "https://youtu.be/rKuezAm7c44?si=WRYNKP87u5ROB_8J",
      image: "https://i.ytimg.com/vi/eMKMFv1-SNo/hqdefault.jpg?s…BACGAY4AUAB&rs=AOn4CLCVaRwhZXK6lYV03A2zyJZlvD_ycA",
      duration: "55:30",
      views: "25.3K",
      isCompleted: true,
      chapter: "Physics - Mechanics",
      difficulty: "intermediate",
    },
    {
      id: 4,
      name: "GFG POTD 28/8/2025",
      time: "55:30",
      type: "youtube",
      link: "https://youtu.be/ZOk-OJpovA0?si=abTC3C2scY0dToWo",
      image: "https://i.ytimg.com/vi/rKuezAm7c44/hqdefault.jpg?s…BACGAY4AUAB&rs=AOn4CLAWeBMRH1idD5CN78REChZFcTfumQ",
      duration: "55:30",
      views: "25.3K",
      isCompleted: true,
      chapter: "Physics - Mechanics",
      difficulty: "intermediate",
    },
    {
      id: 5,
      name: "GFG POTD 29/8/2025",
      time: "55:30",
      type: "youtube",
      link: "https://youtu.be/uLWgzhrwqxE?si=CCLy5KioJNGngQwF",
      image: "https://i.ytimg.com/vi/rKuezAm7c44/hqdefault.jpg?s…BACGAY4AUAB&rs=AOn4CLAWeBMRH1idD5CN78REChZFcTfumQ",
      duration: "55:30",
      views: "25.3K",
      isCompleted: true,
      chapter: "Physics - Mechanics",
      difficulty: "intermediate",
    },
    {
      id: 6,
      name: "GFG POTD 29/8/2025",
      time: "55:30",
      type: "youtube",
      link: "https://youtu.be/sex3ZyedK-c?si=QNAKmOb6JcwlJRRj",
      image: "https://i.ytimg.com/vi/rKuezAm7c44/hqdefault.jpg?s…BACGAY4AUAB&rs=AOn4CLAWeBMRH1idD5CN78REChZFcTfumQ",
      duration: "55:30",
      views: "25.3K",
      isCompleted: true,
      chapter: "Physics - Mechanics",
      difficulty: "intermediate",
    },
  ],
};